# Generated by Django 2.2.1 on 2019-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmedia',
            name='local_path',
        ),
        migrations.AddField(
            model_name='tweetmedia',
            name='local_image',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
