# Generated by Django 2.2.1 on 2019-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190507_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetuser',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
