# Generated by Django 2.2.1 on 2019-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190507_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetuser',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
