# Generated by Django 2.2.1 on 2019-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190507_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmedia',
            name='local_image',
            field=models.ImageField(upload_to='tweet_medias'),
        ),
    ]
